airlinesList = [
  ["TO", "Transavia"],
  ["NI", "Portugalia"],
  ["TP", "Tap Air Portugal"],
  ["IB", "Iberia"],
  ["U2", "Easyjet"],
  ["EC", "Easyjet"],
  ["FR", "Ryanair"],
  ["BA", "British Airways"],
  ["LH", "Lufthansa"],
  ["KL", "KLM"],
  ["LX", "Swiss"],
  ["UX", "Air Europa"],
  ["TK", "Turkish Airlines"],
  ["LW", "Lauda Europe"],
  ["VY", "Vueling"],
  ["S4", "Azores Airlines"],
  ["AY", "Finnair"],
  ["W6", "Wizz Air"],
  ["AT", "Royal Air Maroc"],
  ["DS", "Easyjet Switzerland"],
  ["AF", "Air France"],
];
module.exports = airlinesList;
