airlinesList = [
  ["TO", "Transavia"],
  ["NI", "Portugalia"],
  ["TP", "Tap Air Portugal"],
  ["IB", "Iberia"],
  ["U2", "Easyjet"],
  ["EC", "Easyjet"],
  ["FR", "Ryanair"],
  ["BA", "British Airways"],
  ["LH", "Lufthansa"],
  ["KL", "KLM"],
  ["LX", "Swiss"],
  ["UX", "Air Europa"],
  ["TK", "Turkish Airlines"],
  ["LW", "Lauda Europe"],
  ["VY", "Vueling"],
  ["S4", "Azores Airlines"],
  ["AY", "Finnair"],
  ["W6", "Wizz Air"],
  ["AT", "Royal Air Maroc"],
  ["DS", "Easyjet Switzerland"],
  ["AF", "Air France"],
  ["EW", "EuroWings"],
  ["EI", "Aer Lingus"],
  ["EK", "Emirates"],
  ["W9", "Wizz Air"],
  ["FB", "Bulgaria Air"],
  ["WT", "Swift Air"],
  ["VR", "Cape Verde Airlines"],
  ["SN", "Brussels Airlines"],
  ["HV", "Transavia"],
  ["WN", "Southwest"],
  ["UA", "United Airlines"],
  ["SL", "Thai Lion Air"],
  ["AA", "American Airlines"],
  ["MQ", "Envoy Air"],
  ["NK", "Spirit"],
  ["B6", "JetBlue"],
  ["XE", "JSX"],
  ["OD", "Malindo Air"],
  ["AK", "Air Asia"],
  ["VS", "Virgin Atlantic"],
  ["DL", "Delta"],
  ["YV", "Mesa Air!"],
  ["AS", "Alaska Airlines"],
  ["OO", "SkyWest Airlines"],
  ["QZ", "Indonesia AirAsia"],
  ["FD", "Thai AirAsia"],
  ["DD", "Nok Air"],
  ["HO", "Juneyao Airlines"],
  ["QF", "Qantas"],
  ["TG", "Thai Airways"],
  ["CX", "Cathay Pacific"],
  ["VZ", "Thai Vietjet Air"],
  ["WE", "Thai Smile"],
  ["MH", "Malaysia Airlines"],
  ["SV", "Saudi"],
  ["PG", "Bangkok Airways"],
  ["9C", "Spring"],
  ["QR", "Qater"],
  ["UO", "Hong Kong Express"],
  ["ID", "Batik Air"],
  ["VN", "Vietnam Airlines"],
  ["VJ", "VietJet Air"],
  ["KR", "Cambodia Airways"],
  ["UK", "Vistara"],
  ["6E", "Indigo"],
  ["WY", "Oman Air"],
  ["KE", "Korean Air"],
  ["XJ", "Thai AirAsia X"],
  ["JL", "Japan Airlines"],
  ["NQ", "Air Japan"],
  ["CI", "China Airlines"],
  ["SQ", "Singapore Airlines"],
  ["GF", "Gulf Air"],
  ["TR", "Scoot"],
  ["CK", "China Cargo Airlines"],
  ["LQ", "Lanmei Airlines Cambodia"],
  ["RH", "Hong Kong Air Cargo"],
  ["ZA", "Sky Angkor"],
  ["BG", "Biman"],
  ["5J", "Cebu Pacific"],
  ["JX", "Starlux"],
  ["3K", "Jetstar"],
  ["KZ", "Nippon Cargo Airlines"],
  ["QH", "Bamboo Airways"],
  ["BR", "Eva Air"],
  ["3U", "Sichuan Airlines"],
  ["HB", "Asia Atlantic Airlines"],
  ["QX", "Horizon Air"],
  ["AC", "Air Canada"],
  ["G$", "Allegiant"],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
];
module.exports = airlinesList;
