airlinesList = [
  ["TO", "Transavia"],
  ["NI", "Portugalia"],
  ["TP", "Tap Air Portugal"],
  ["IB", "Iberia"],
  ["U2", "Easyjet"],
  ["EC", "Easyjet"],
  ["FR", "Ryanair"],
  ["BA", "British Airways"],
  ["LH", "Lufthansa"],
  ["KL", "KLM"],
  ["LX", "Swiss"],
  ["UX", "Air Europa"],
  ["TK", "Turkish Airlines"],
  ["LW", "Lauda Europe"],
  ["VY", "Vueling"],
  ["S4", "Azores Airlines"],
  ["AY", "Finnair"],
  ["W6", "Wizz Air"],
  ["AT", "Royal Air Maroc"],
  ["DS", "Easyjet Switzerland"],
  ["AF", "Air France"],
  ["EW", "EuroWings"],
  ["EI", "Aer Lingus"],
  ["EK", "Emirates"],
  ["W9", "Wizz Air"],
  ["FB", "Bulgaria Air"],
  ["WT", "Swift Air"],
  ["VR", "Cape Verde Airlines"],
  ["SN", "Brussels Airlines"],
  ["HV", "Transavia"],
  ["WN", "Southwest"],
  ["UA", "United Airlines"],
  ["SL", "Thai Lion Air"],
  ["AA", "American Airlines"],
  ["MQ", "Envoy Air"],
  ["NK", "Spirit"],
  ["B6", "JetBlue"],
  ["XE", "JSX"],
  ["OD", "Malindo Air"],
  ["AK", "Air Asia"],
  ["VS", "Virgin Atlantic"],
  ["DL", "Delta"],
  ["YV", "Mesa Air!"],
  ["AS", "Alaska Airlines"],
  ["OO", "SkyWest Airlines"],
  ["QZ", "Indonesia AirAsia"],
  ["FD", "Thai AirAsia"],
  ["DD", "Nok Air"],
  ["HO", "Juneyao Airlines"],
  ["QF", "Qantas"],
  ["TG", "Thai Airways"],
  ["CX", "Cathay Pacific"],
  ["VZ", "Thai Vietjet Air"],
  ["WE", "Thai Smile"],
  ["MH", "Malaysia Airlines"],
  ["SV", "Saudi"],
  ["PG", "Bangkok Airways"],
  ["9C", "Spring"],
  ["QR", "Qatar"],
  ["UO", "Hong Kong Express"],
  ["ID", "Batik Air"],
  ["VN", "Vietnam Airlines"],
  ["VJ", "VietJet Air"],
  ["KR", "Cambodia Airways"],
  ["UK", "Vistara"],
  ["6E", "Indigo"],
  ["WY", "Oman Air"],
  ["KE", "Korean Air"],
  ["XJ", "Thai AirAsia X"],
  ["JL", "Japan Airlines"],
  ["NQ", "Air Japan"],
  ["CI", "China Airlines"],
  ["SQ", "Singapore Airlines"],
  ["GF", "Gulf Air"],
  ["TR", "Scoot"],
  ["CK", "China Cargo Airlines"],
  ["LQ", "Lanmei Airlines Cambodia"],
  ["RH", "Hong Kong Air Cargo"],
  ["ZA", "Sky Angkor"],
  ["BG", "Biman"],
  ["5J", "Cebu Pacific"],
  ["JX", "Starlux"],
  ["3K", "Jetstar"],
  ["KZ", "Nippon Cargo Airlines"],
  ["QH", "Bamboo Airways"],
  ["BR", "Eva Air"],
  ["3U", "Sichuan Airlines"],
  ["HB", "Asia Atlantic Airlines"],
  ["QX", "Horizon Air"],
  ["AC", "Air Canada"],
  ["G4", "Allegiant"],
  ["X5", "Air Europa Express"],
  ["F9", "Frontier"],
  ["AD", "Azul"],
  ["DY", "Norwegina Air Shuttle"],
  ["6O", "Orbest"],
  ["QS", "Smartwings"],
  ["ZQ", "German Airways"],
  ["LG", "LuxAir"],
  ["9E", "Endeavor"],
  ["CZ", "China Southern"],
  ["CA", "Air China"],
  ["GJ", "Zhejiang Loong Airlines"],
  ["FM", "Shanghai Airlines"],
  ["MU", "China Eastern"],
  ["SG", "SpiceJet"],
  ["B3", "Bhutan Airlines"],
  ["ZH", "Shenzen Airlines"],
  ["FY", "Firefly"],
  ["8M", "Myanmar Airways"],
  ["PR", "Philippine Airlines"],
  ["KY", "Kunming Airlines"],
  ["HX", "Hong Kong Airlines"],
  ["AQ", "9air"],
  ["SU", "Aeroflot"],
  ["OM", "Mongolian Airlines"],
  ["EY", "Etihad"],
  ["AI", "Air India"],
  ["HU", "Hainan"],
  ["PN", "West Air"],
  ["JQ", "Jetstar"],
  ["OS", "Austrian"],
  ["WX", "CityJet"],
  ["SK", "SAS"],
  ["D8", "Norwegian"],
  ["CJ", "British Airways"],
  ["T3", "Eastern Airways"],
  ["OR", "TUI"],
  ["CL", "Lufthansa"],
  ["EN", "Air Dolomiti"],
  ["I2", "Iberia"],
  ["PC", "Pegasus"],
  ["AZ", "ITA Airways"],
  ["A3", "Aegean Airlines"],
  ["MF", "Xiamen Air"],
  ["EZ", "Easyjet"],
  ["MS", "EgyptAir"],
  ["EJ", "EasyJet"],
  ["BT", "Air Baltic"],
  ["KM", "Malta Airlines"],
  ["LO", "LOT Polish Airlines"],
  ["MN", "MNG Airlines"],
  ["OU", "Croatia Airlines"],
  ["RO", "Tarom"],
  ["5Y", "Atlas Air"],
  ["WA", "KLM"],
  ["OG", "Play"],
  ["XC", "Corendon"],
  ["FI", "Icelandair"],
  ["GA", "Garuda Indonesia"],
  ["VF", "AJet"],
  ["CD", "Corendon"],
  ["AM", "AeroMexico"],
  ["3O", "Air Arabia"],
  ["JU", "Getjet"],
  ["LY", "El Al"],
  ["XQ", "SunExpress"],
  ["7L", "Silk Way West Airlines"],
  ["KQ", "Kenya Airways"],
  ["GQ", "SKY express"],
  ["MP", "MartinAir"],
  ["PY", "Surinaamse Luchtvaart Maatschappij"],
  ["IZ", "Arkia"],
  ["CV", "Cargolux"],
  ["", ""],
  ["", ""],
  ["", ""],
];
module.exports = airlinesList;
