airportsList = [
  ["ORY", "Paris Orly"],
  ["MAD", "Madrid"],
  ["BCN", "Barcelona"],
  ["OPO", "Porto"],
  ["AMS", "Amsterdam"],
  ["FNC", "Funchal"],
  ["LHR", "London Heathrow"],
  ["GVA", "Geneva"],
  ["BRU", "Brussels"],
  ["RAK", "Marrakesh"],
  ["MUC", "Munich"],
  ["IST", "Istanbul"],
  ["FRA", "Frankfurt"],
  ["CIA", "Rome Ciampino"],
  ["CDG", "Paris Charles de Gaulle"],
  ["VIE", "Vienna"],
  ["TER", "Terceira Azores"],
  ["BIO", "Bilbao"],
  ["STN", "London Stansted"],
  ["HEL", "Helsinki"],
  ["ZRH", "Zurich"],
  ["PDL", "Ponta Delgada"],
  ["SOF", "Sofia"],
  ["LGW", "London Gatwick"],
  ["NCE", "Nice"],
  ["BOD", "Bordeaux"],
  ["BER", "Berlin"],
  ["CRL", "Brussels Charleroi"],
  ["CMN", "Casablanca"],
  ["LYS", "Lyon"],
  ["DUB", "Dublin"],
  ["LPA", "Las Palmas Gran Canaria"],
  ["HAM", "Hamburg"],
  ["MXP", "Milan Malpensa"],
  ["MRS", "Marseille"],
  ["FCO", "Rome Fiumicino"],
  ["SVQ", "Seville"],
  ["VCE", "Venice"],
  ["DUS", "Dusseldorf"],
  ["MAN", "Manchester"],
  ["ARN", "Stockholm Arlanda"],
  ["WAW", "Warsaw"],
  ["LAD", "Luanda"],
  ["LUX", "Luxembourg"],
  ["ALC", "Alicante"],
  ["FAO", "Faro"],
  ["BVA", "Paris Beauvais"],
  ["NTE", "Nantes"],
  ["DXB", "Dubai"],
  ["VLC", "Valencia"],
  ["RAI", "Praia Cape Verde"],
  ["LTN", "London Luton"],
  ["CPH", "Copenhagen"],
  ["FLR", "Florence"],
  ["TLS", "Toulouse"],
  ["PRG", "Prague"],
  ["AGP", "Malaga"],
  ["BLQ", "Bologna"],
  ["SID", "Sal Cape Verde"],
  ["VXE", "Sao Vicente Cape Verde"],
  ["CGK", "Jakarta"],
  ["DFW", "Dallas Fort Worth"],
  ["IAD", "Washington Dulles"],
  ["PHX", "Phoenix"],
  ["DAL", "Dallas Love Field"],
  ["DTW", "Detroit"],
  ["IAH", "Houston George Bush"],
  ["HOU", "Houston Hobby"],
  ["BNA", "Nashville"],
  ["SAN", "San Diego"],
  ["BOS", "Boston Logan"],
  ["BWI", "Baltimore Washington"],
  ["RDI", "Raleigh–Durham"],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
];
module.exports = airportsList;
