airportsList = [
  ["ORY", "Paris Orly"],
  ["MAD", "Madrid"],
  ["BCN", "Barcelona"],
  ["OPO", "Porto"],
  ["AMS", "Amsterdam"],
  ["FNC", "Funchal"],
  ["LHR", "London Heathrow"],
  ["GVA", "Geneva"],
  ["BRU", "Brussels"],
  ["RAK", "Marrakesh"],
  ["MUC", "Munich"],
  ["IST", "Istanbul"],
  ["FRA", "Frankfurt"],
  ["CIA", "Rome Ciampino"],
  ["CDG", "Paris Charles de Gaulle"],
  ["VIE", "Vienna"],
  ["TER", "Terceira Azores"],
  ["BIO", "Bilbao"],
  ["STN", "London Stansted"],
  ["HEL", "Helsinki"],
  ["ZRH", "Zurich"],
  ["PDL", "Ponta Delgada"],
  ["SOF", "Sofia"],
  ["LGW", "London Gatwick"],
  ["NCE", "Nice"],
  ["BOD", "Bordeaux"],
  ["BER", "Berlin"],
  ["CRL", "Brussels Charleroi"],
  ["CMN", "Casablanca"],
  ["LYS", "Lyon"],
];
module.exports = airportsList;
